-- Create the contact_submissions table
CREATE TABLE IF NOT EXISTS contact_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  email TEXT,
  message TEXT,
  submitted_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable read access for all users (optional - for admin panel viewing)
-- GRANT SELECT ON contact_submissions TO anon;

-- Enable insert access for all users (needed for form submissions)
GRANT INSERT ON contact_submissions TO anon;

-- Enable RLS (Row Level Security) if you want to add more security
-- ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;